using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.Extensions.Logging;
using Microsoft.UI.Xaml;
using TorrentApp.Models;
using TorrentApp.Services;

namespace TorrentApp.ViewModels;

/// <summary>
/// ViewModel for the Downloads page. Manages the torrent list and all torrent actions.
/// A background timer polls the engine every 500 ms to refresh statistics efficiently.
/// </summary>
public sealed partial class DownloadsViewModel : ObservableObject, IDisposable
{
    private readonly ITorrentService _torrentService;
    private readonly ISettingsService _settingsService;
    private readonly ILogger<DownloadsViewModel> _logger;

    // Statistics refresh timer — 500 ms interval.
    private readonly DispatcherTimer _refreshTimer;

    // Full torrent list backing collection.
    public ObservableCollection<TorrentItemViewModel> Torrents { get; } = [];

    // The currently selected torrent (drives detail panel).
    [ObservableProperty]
    public partial TorrentItemViewModel? SelectedTorrent { get; set; }

    // UI state flags
    [ObservableProperty]
    public partial bool IsEmpty { get; set; } = true;

    /// <summary>Inverse of <see cref="IsEmpty"/> — used for list visibility binding.</summary>
    public bool IsNotEmpty => !IsEmpty;

    [ObservableProperty]
    public partial bool IsAddingTorrent { get; set; }

    [ObservableProperty]
    public partial string StatusMessage { get; set; } = string.Empty;

    /// <summary>True when there is a non-empty status message to display.</summary>
    public bool HasStatusMessage => !string.IsNullOrEmpty(StatusMessage);

    // Raise HasStatusMessage whenever StatusMessage changes (generated by CT.Mvvm)
    partial void OnStatusMessageChanged(string value) =>
        OnPropertyChanged(nameof(HasStatusMessage));

    // -----------------------------------------------------------------------
    // Constructor
    // -----------------------------------------------------------------------

    public DownloadsViewModel(
        ITorrentService torrentService,
        ISettingsService settingsService,
        ILogger<DownloadsViewModel> logger)
    {
        _torrentService = torrentService;
        _settingsService = settingsService;
        _logger = logger;

        // Subscribe to engine events to add/remove items reactively.
        _torrentService.TorrentAdded += OnTorrentAdded;
        _torrentService.TorrentRemoved += OnTorrentRemoved;
        _torrentService.TorrentStateChanged += OnTorrentStateChanged;
        _torrentService.TorrentCompleted += OnTorrentCompleted;

        // Load existing torrents already in the engine (restored from disk).
        foreach (TorrentItem item in _torrentService.GetAllTorrents())
        {
            Torrents.Add(new TorrentItemViewModel(item));
        }

        IsEmpty = Torrents.Count == 0;

        // Start polling timer on the UI thread.
        _refreshTimer = new DispatcherTimer
        {
            Interval = TimeSpan.FromMilliseconds(500),
        };
        _refreshTimer.Tick += OnRefreshTimerTick;
        _refreshTimer.Start();
    }

    // -----------------------------------------------------------------------
    // Commands — Add Torrent (file)
    // -----------------------------------------------------------------------

    [RelayCommand]
    public async Task AddTorrentFileAsync(string torrentFilePath)
    {
        if (string.IsNullOrWhiteSpace(torrentFilePath))
        {
            return;
        }

        IsAddingTorrent = true;
        StatusMessage = string.Empty;

        try
        {
            string savePath = _settingsService.Settings.DefaultSavePath;
            Directory.CreateDirectory(savePath);

            TorrentItem item = await _torrentService
                .AddTorrentFileAsync(torrentFilePath, savePath)
                .ConfigureAwait(true);

            await _torrentService.StartAsync(item.InfoHash).ConfigureAwait(true);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to add torrent file {Path}", torrentFilePath);
            StatusMessage = "Could not add the torrent file. Please check the file and try again.";
        }
        finally
        {
            IsAddingTorrent = false;
        }
    }

    // -----------------------------------------------------------------------
    // Commands — Add Magnet Link
    // -----------------------------------------------------------------------

    [RelayCommand]
    public async Task AddMagnetLinkAsync(string magnetUri)
    {
        if (string.IsNullOrWhiteSpace(magnetUri))
        {
            return;
        }

        IsAddingTorrent = true;
        StatusMessage = string.Empty;

        try
        {
            string savePath = _settingsService.Settings.DefaultSavePath;
            Directory.CreateDirectory(savePath);

            TorrentItem item = await _torrentService
                .AddMagnetLinkAsync(magnetUri, savePath)
                .ConfigureAwait(true);

            await _torrentService.StartAsync(item.InfoHash).ConfigureAwait(true);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to add magnet link.");
            StatusMessage = "Could not add the magnet link. Please check the link and try again.";
        }
        finally
        {
            IsAddingTorrent = false;
        }
    }

    // -----------------------------------------------------------------------
    // Commands — Start
    // -----------------------------------------------------------------------

    [RelayCommand]
    public async Task StartTorrentAsync(TorrentItemViewModel? vm)
    {
        if (vm is null)
        {
            return;
        }

        try
        {
            await _torrentService.StartAsync(vm.InfoHash).ConfigureAwait(true);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to start torrent {Hash}", vm.InfoHash);
            StatusMessage = $"Could not start \"{vm.Name}\". Please try again.";
        }
    }

    // -----------------------------------------------------------------------
    // Commands — Pause
    // -----------------------------------------------------------------------

    [RelayCommand]
    public async Task PauseTorrentAsync(TorrentItemViewModel? vm)
    {
        if (vm is null)
        {
            return;
        }

        try
        {
            await _torrentService.PauseAsync(vm.InfoHash).ConfigureAwait(true);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to pause torrent {Hash}", vm.InfoHash);
            StatusMessage = $"Could not pause \"{vm.Name}\". Please try again.";
        }
    }

    // -----------------------------------------------------------------------
    // Commands — Remove
    // -----------------------------------------------------------------------

    [RelayCommand]
    public async Task RemoveTorrentAsync((TorrentItemViewModel vm, bool deleteFiles) args)
    {
        try
        {
            await _torrentService
                .RemoveAsync(args.vm.InfoHash, args.deleteFiles)
                .ConfigureAwait(true);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to remove torrent {Hash}", args.vm.InfoHash);
            StatusMessage = $"Could not remove \"{args.vm.Name}\". Please try again.";
        }
    }

    // -----------------------------------------------------------------------
    // Commands — Open folder
    // -----------------------------------------------------------------------

    [RelayCommand]
    public static void OpenFolder(TorrentItemViewModel? vm)
    {
        if (vm is null || string.IsNullOrWhiteSpace(vm.SavePath))
        {
            return;
        }

        if (Directory.Exists(vm.SavePath))
        {
            System.Diagnostics.Process.Start("explorer.exe", vm.SavePath);
        }
    }

    // -----------------------------------------------------------------------
    // Timer tick — statistics refresh
    // -----------------------------------------------------------------------

    private void OnRefreshTimerTick(object? sender, object e)
    {
        // Pull fresh stats from MonoTorrent into the app-owned models.
        _torrentService.RefreshStatistics();

        // Update each ViewModel. Only changed observable properties fire events.
        foreach (TorrentItemViewModel vm in Torrents)
        {
            vm.SyncFromModel();
        }
    }

    // -----------------------------------------------------------------------
    // Engine event handlers — dispatched to UI thread
    // -----------------------------------------------------------------------

    private void OnTorrentAdded(object? sender, TorrentItem item)
    {
        App.DispatcherQueue.TryEnqueue(() =>
        {
            // Avoid duplicates (engine may fire multiple times for same hash)
            if (Torrents.Any(vm => vm.InfoHash == item.InfoHash))
            {
                return;
            }

            Torrents.Add(new TorrentItemViewModel(item));
            IsEmpty = false;
            OnPropertyChanged(nameof(IsNotEmpty));
        });
    }

    private void OnTorrentRemoved(object? sender, string infoHash)
    {
        App.DispatcherQueue.TryEnqueue(() =>
        {
            TorrentItemViewModel? vm = Torrents.FirstOrDefault(v => v.InfoHash == infoHash);
            if (vm is not null)
            {
                Torrents.Remove(vm);
            }

            if (SelectedTorrent?.InfoHash == infoHash)
            {
                SelectedTorrent = null;
            }

            IsEmpty = Torrents.Count == 0;
            OnPropertyChanged(nameof(IsNotEmpty));
        });
    }

    private void OnTorrentStateChanged(object? sender, TorrentItem item)
    {
        // Statistics are polled via the timer — state changes just sync the VM.
        App.DispatcherQueue.TryEnqueue(() =>
        {
            TorrentItemViewModel? vm = Torrents.FirstOrDefault(v => v.InfoHash == item.InfoHash);
            vm?.SyncFromModel();
        });
    }

    private void OnTorrentCompleted(object? sender, TorrentItem item)
    {
        _logger.LogInformation("Torrent completed in UI: {Name}", item.Name);
        App.DispatcherQueue.TryEnqueue(() =>
        {
            TorrentItemViewModel? vm = Torrents.FirstOrDefault(v => v.InfoHash == item.InfoHash);
            vm?.SyncFromModel();
        });
    }

    // -----------------------------------------------------------------------
    // IDisposable
    // -----------------------------------------------------------------------

    public void Dispose()
    {
        _refreshTimer.Stop();
        _refreshTimer.Tick -= OnRefreshTimerTick;

        _torrentService.TorrentAdded -= OnTorrentAdded;
        _torrentService.TorrentRemoved -= OnTorrentRemoved;
        _torrentService.TorrentStateChanged -= OnTorrentStateChanged;
        _torrentService.TorrentCompleted -= OnTorrentCompleted;
    }
}
